name: deepLearn

channels:
- conda-forge
- anaconda
- pytorch

dependencies:
# Essential
- python==3.7.6
- tqdm==4.41.1
- nb_conda_kernels==2.2.0
- pip==19.3.1
- ipython==7.1.1
# Data Science
- numpy==1.18.1
- scipy==1.3.0
- pandas==0.25.3
# Machine Learning
- scikit-learn==0.22
# Visualization
- matplotlib==3.1.2
- ipywidgets==7.4.2
# Deep Learning
- pytorch
# Computer Vision
- torchvision
- pillow


